### ISSUE TITLE
How to get equivalent behaviour in 4.0/4.1 as with overlapping TriggerShapes from 3.x

### ISSUE THREAD

**Issue by sar283** [NVIDIAGameWorks/PhysX#117]
Hi,

in PhysX 3.4 it was possible to get the OnTrigger-Callback from overlapping TriggerShapes. 

I don't need physically correct behavoiur from my actors. I just want to determine if there is a collision between them or not. I am using TriggerShapes in 3.4 because i can get a better performance,regarding simulation time, than with RigidDynamic-Actors.

Since TriggerShape vs. TriggerShape is deprecated in 4 and 4.1, is there a similar ways to achive the described behaviour?

Thanks in advance for any help.

**Comment by K-Tone** [comment]
Just for the future generations running into the issue: the online manual has it mentioned that the recommended workaround is to duplicate shapes:

> PxSceneFlag::eDEPRECATED_TRIGGER_TRIGGER_REPORTS has been removed. It is recommended to use a trigger and a non-trigger shape, both with the same geometry and local pose, to emulate getting notifications for overlaps between trigger shapes.

https://gameworksdocs.nvidia.com/PhysX/4.1/documentation/physxguide/Manual/MigrationTo40.html#core-physx
