### ISSUE TITLE
Why the scale coefficient for CCT's underlying kinematic actor should be smaller than 1.0?

### ISSUE THREAD

**Issue by ghost** [NVIDIAGameWorks/PhysX#122]
Hi,

A underlying kinematic actor is created during CCT's creation, and the scale coefficient for it can be set in PxControllerDesc.
Due to the comment, it should be set for a number smaller than 1.0 but the reason is not explained.
We are considering to use 1.0 for this if there is not any artifact so we wonder why 1.0 is not recommended.

Thanks for any advise!

**Comment by karjonas** [comment]
see #645
