### ISSUE TITLE
Physx 4.1 - d6 joint limit bug

### ISSUE THREAD

**Issue by iaiotom** [NVIDIAGameWorks/PhysX#124]
Hello,
I found probably a bug with physx 4.1. I have 2 rigid bodies and one d6 joint with a limit of -60,60 degrees on the Z axis. The joint has a rotation of -45 degrees. During the simulation seems that the SwingZAngle is compute ignoring the rotation of the joint and so the solver apply a wrong limit. You can see the problem from the image I've attached and from the pvd session.

[armd_d6_limit_debug.zip](https://github.com/NVIDIAGameWorks/PhysX/files/3199271/armd_d6_limit_debug.zip)

 
![physx41_d6_bug_1](https://user-images.githubusercontent.com/2465995/58043781-0262f180-7b36-11e9-8cad-38f2f6449d37.jpg)
![physx41_d6_bug_2](https://user-images.githubusercontent.com/2465995/58043784-042cb500-7b36-11e9-8e34-783ec4c0f83e.jpg)

**Comment by iaiotom** [comment]
I've found that inside the static PxU32 D6JointSolverPrep(…) function the PxQuat swing variable is computed without consider the constraint rotation and since the angle limit check is using this quaternion to check the boundaries I get the problem I show before.

**Comment by kstorey-nvidia** [comment]
Are you sure that it is computed without considering the constraint rotation? Swing/twist are decomposed from cB2cA transform, which is computed from cA2w and cB2w transforms, which are the joint frames transformed into world space. These are computed as a byproduct of the ConstraintHelper constructor. 

Are you certain that the joint frames have been correctly configured and exported from Maya?
