### ISSUE TITLE
PhysX 4.1 crashing on release. 

### ISSUE THREAD

**Issue by tomerze** [NVIDIAGameWorks/PhysX#127]
I updated my engine to PhysX 4.1 from PhysX 4.0. (The code using PhysX didn't change).
When I run on debug everything is working normally. When I run on release PhysX crash after about a second. The simulation is working as it should at that second (As far as I can tell). 

Exception details:
> Exception thrown at 0x00007FF95C582D7B (PhysXCommon_64.dll) in Application.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF. occurred
its at line 58 at the file PsVecTransform.h 
here's the function throwing it:
```
PX_FORCE_INLINE PsTransformV(const Vec3VArg p0 = V3Zero(), const QuatVArg q0 = QuatIdentity()) : q(q0), p(p0)
{
	PX_ASSERT(isSaneQuatV(q0));
}

```
*Note all the scene is rendering in purple (when on release mode only) since physX has nothing to do with rendering I assume this is a bug on my side. 

I use the release libs and dlls for release and the debug libs and dlls for debug.
My preset is vs14win64 but I changed the cmake switch "NV_USE_STATIC_WINCRT" to "False"
My platform is windows 10. Running a 64-bit version of PhysX.
Using PhysX on the CPU. 
I use these libs
                PhysXCommon_64.lib
		PhysX_64.lib
		PhysXFoundation_64.lib
		PhysXExtensions_static_64.lib
		PhysXCooking_64.lib

Not sure if PhysX is logging errors since my logging is totally off on release mode. I can try to enable it somehow if needed. 

EDIT: 
this seems to be related to a convex mesh attached to a rigid-body colliding with a box collider attached to a rigid-body with mass zero, inertia zero and PxActorFlag::eDISABLE_GRAVITY set to true. 
View:
![demo](https://user-images.githubusercontent.com/45238974/58540783-ba616000-8202-11e9-9311-3e1e10f70b12.gif)

How to solve:
As suggested by @cmp I updated Visual studio 2019 from version 16.0.3 to version 16.1.1 and recompiled PhysX release

**Comment by kstorey-nvidia** [comment]
Are there any errors logged by the debug build? Debug and checked PhysX both validate user input and throw away illegal parameters while logging warnings. All this validation is removed in release build.

Could you try linking against the checked build config to see if the issue repeats or perhaps there are errors logged by PhysX?

If the above doesn't help identify the issue, could you please provide a callstack?

**Comment by tomerze** [comment]
No errors logged by the debug build. The debug build is working perfectly just as PhysX 4.0 did. 

The checked build is, unfortunately, using the  MdRelease runtime. while the debug config of my engine uses the MdDebug runtime. 

So I can't link PhysX checked to my debug config. But I can link physX checked to the release config of my engine. It crashes too.

> Exception thrown at 0x00007FF950FD3E6B (PhysXCommon_64.dll) in Application.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

Added a small check to my logging system no errors or warnings are logged at any configuration of physX or my engine (including PhysX checked).

Changed the Convex Mesh collider(PxConvexMesh) to a box collider (PxBoxGeometry). Every config is working perfectly. The issue seems to be exclusive to PxConvexMesh collision. 

*Note :
My application is using the console subsystem on debug but using the windows subsystem on release. 
I use PhysX debug for my debug config and I use PhysX release for my release config as expected. 
Call stack:
```
>	[Inline Frame] PhysXCommon_64.dll!physx::shdfnd::aos::V4ClearW(const __m128) Line 58	C++
 	[Inline Frame] PhysXCommon_64.dll!physx::shdfnd::aos::Vec3V_From_Vec4V(__m128) Line 181	C++
 	[Inline Frame] PhysXCommon_64.dll!physx::shdfnd::aos::V3LoadU_SafeReadW(const physx::PxVec3 &)	C++
 	PhysXCommon_64.dll!physx::Gu::pcmContactBoxConvex(const physx::Gu::GeometryUnion & shape0, const physx::Gu::GeometryUnion & shape1, const physx::PxTransform & transform0, const physx::PxTransform & transform1, const physx::Gu::NarrowPhaseParams & params, physx::Gu::Cache & cache, physx::Gu::ContactBuffer & contactBuffer, physx::Cm::RenderOutput * renderOutput) Line 178	C++
 	[Inline Frame] PhysX_64.dll!discreteNarrowPhase(physx::PxcNpThreadContext &) Line 408	C++
 	PhysX_64.dll!physx::PxcDiscreteNarrowPhasePCM(physx::PxcNpThreadContext & context, const physx::PxcNpWorkUnit & input, physx::Gu::Cache & cache, physx::PxsContactManagerOutput & output) Line 445	C++
 	PhysX_64.dll!PxsCMDiscreteUpdateTask::processCms<&physx::PxcDiscreteNarrowPhasePCM>(physx::PxcNpThreadContext * threadContext) Line 440	C++
 	PhysX_64.dll!PxsCMDiscreteUpdateTask::runInternal() Line 513	C++
 	PhysX_64.dll!physx::Cm::Task::run() Line 67	C++
 	Application.exe!physx::Ext::CpuWorkerThread::execute() Line 97	C++
 	PhysXFoundation_64.dll!physx::shdfnd::`anonymous namespace'::PxThreadStart(void * arg) Line 102	C++
 	[External Code]	
```

**Comment by cmp-** [comment]
Are you compiling with a Visual Studio 2019 version earlier than 16.1 by any chance? There was a bug that optimized out unaligned loads, which generates exactly that error (Access violation reading location 0xFFFFFFFFFFFFFFFF).

**Comment by tomerze** [comment]
@cmp Yes. I am compiling with Visual Studio 2019 16.0.3. I'll update Visual Studio and recompile PhysX.

**Comment by tomerze** [comment]
Updating Visual Studio 2019 to version 16.1.1 and recompiling PhysX release solved the issue.
