### ISSUE TITLE
Use different normal than positive x for PxPlaneGeometry

### ISSUE THREAD

**Issue by runpiw** [NVIDIAGameWorks/PhysX#130]
Is it possible to pass in different normal for PxPlaneGeometry instead of the default (1,0,0,0) equation.

**Comment by kstorey-nvidia** [comment]
No, but you can rotate and translate the plane by providing either a local pose on the shape or a global pose on the actor to place the planes in any configuration you like.

There is a utility function to help you compute an appropriate transform:

PX_PHYSX_COMMON_API PxTransform PxTransformFromPlaneEquation(const PxPlane& plane)
