### ISSUE TITLE
compile result confused aboud MTd(multithread debug) and MDd(multithread debug dll)

### ISSUE THREAD

**Issue by RPG3D** [NVIDIAGameWorks/PhysX#135]
![QQ图片20190606163455](https://user-images.githubusercontent.com/7828382/59018689-0a7e9900-8879-11e9-917f-1322ad26f726.png)

some is MTd some id MDd

then link error
![QQ图片20190606163553](https://user-images.githubusercontent.com/7828382/59018745-2e41df00-8879-11e9-896c-9134904429b0.png)

**Comment by RPG3D** [comment]
![image](https://user-images.githubusercontent.com/7828382/59018875-77922e80-8879-11e9-84a3-bfe4afb02752.png)

**Comment by AlesBorovicka** [comment]
Hi,
 looking at the output, it says that PhysX is compiled with MT/MTd. Which seems to be true, as the libraries of PhysX are in bin/win.x86_64.vc141.mt
But your application seems to compile with MD (Main.obj). So either change your app to use MT, or switch PhysX to compile MD:
set NV_USE_STATIC_WINCRT to False

**Comment by RPG3D** [comment]
got it thanks

**Comment by RPG3D** [comment]
resolved
