### ISSUE TITLE
Articulation Collision Detection & Contact Reporting

### ISSUE THREAD

**Issue by Tadinu** [NVIDIAGameWorks/PhysX#141]
https://gameworksdocs.nvidia.com/PhysX/4.0/documentation/PhysXGuide/Manual/AdvancedCollisionDetection.html#contact-reporting

Could you give some specific reference on how to do this for the articulation?
Would it work also if I use `PxSimulationEventCallback` for `PxArticulationLink` in `PxArticulationReducedCoordinate`/`PxArticulation` to do the contact reporting?

**Comment by kstorey-nvidia** [comment]
Getting contact reports for articulation links is exactly the same as getting them for rigid bodies. You should just be able to follow the guide for contact reporting for rigid bodies and it will also apply to articulation links.
