### ISSUE TITLE
Generating Projects and CMake

### ISSUE THREAD

**Issue by CogSimGuy** [NVIDIAGameWorks/PhysX#16]
Getting an error of not specifying PHYSX_ROOT_DIR when running generate_projects.bat

After I create and set to the ../physx directory of my project folder, I get further cmake errors with respect to NV_USE_GAMEWORKS_OUTPUT_DIRS?

Anybody know some magic I'm missing....?

**Comment by AlesBorovicka** [comment]
Not sure what you are trying, but PHYSX_ROOT_DIR is set in the generate_projects.bat.

When you sync the project, you go into the physx directory and run there generate_projects.bat there, it will set the required variables. Note that you cannot call /physx/generate_projects.bat for now, we will fix that when we are back from holidays.

**Comment by CogSimGuy** [comment]
Ok thanks, I was calling /physx/generate_projects.bat and getting these issues...I'll wait for the fix.

**Comment by AlesBorovicka** [comment]
Fix should be there
