### ISSUE TITLE
Robotics demo

### ISSUE THREAD

**Issue by michaelchi08** [NVIDIAGameWorks/PhysX#161]
Hello,

Was the source code for the robotics demo released?
https://www.youtube.com/watch?v=K1rotbzekf0

_Originally posted by @michaelchi08 in https://github.com/NVIDIAGameWorks/PhysX/issues/6#issuecomment-519623590_

**Comment by Sposito** [comment]
Thats already solved on https://github.com/NVIDIAGameWorks/PhysX/issues/6#issuecomment-519625343
Can someone close it here please?
