### ISSUE TITLE
PsAllocator.h(40,11) : fatal error C1083: Cannot open include file: 'typeinfo.h': No such file or directory

### ISSUE THREAD

**Issue by ericwj** [NVIDIAGameWorks/PhysX#164]
It'll build with [`#include <typeinfo.h>`](https://github.com/NVIDIAGameWorks/PhysX/blob/4050bbfdc2699dfab7edbf0393df8ff96bbe06c5/physx/source/foundation/include/PsAllocator.h#L38-L44) changed to `#include <typeinfo>` on line 40.

**Comment by StephanTLavavej** [comment]
This is because I removed the non-Standard header `<typeinfo.h>` from MSVC. Including `<typeinfo>` is the correct fix, and is compatible with all versions of MSVC (going back at least a decade).

**Comment by SeanMaxhell** [comment]
I have a similar Problem with Visual Studio 2019 and Unreal Engine Oculus Integration.
But I don't understand what I have to do to solve it.
Any Help?

**Comment by ericwj** [comment]
If you have 'a similar' problem then you have to be more specific or even open another issue.

If you have the exact same problem then you can literally open `PsAllocator.h`, go to line 40 and remove `.h` from that line.

**Comment by kornellvarga** [comment]
> It'll build with [`#include <typeinfo.h>`](https://github.com/NVIDIAGameWorks/PhysX/blob/4050bbfdc2699dfab7edbf0393df8ff96bbe06c5/physx/source/foundation/include/PsAllocator.h#L38-L44) changed to `#include <typeinfo>` on line 40.

Hmm its all fine and works, but what I do not understand is when a change like this happens why is there no follow-up for references such as the PsAllocator.h.
It would cost 5 min to push a changed version, and save half an hour each person who is as unexperienced as I am.

**Comment by xcplay** [comment]
I find all the answers, you can see it here. https://blog.csdn.net/weixinyi21cn/article/details/108035285

**Comment by ericwj** [comment]
Looks like #181 fixed this.

Haven't tested it so let me know if its true then I'll close this.

**Comment by mastercoms** [comment]
Yep it's fixed

**Comment by ericwj** [comment]
ty
