### ISSUE TITLE
Question about TriangleMesh collision problem

### ISSUE THREAD

**Issue by utilForever** [NVIDIAGameWorks/PhysX#166]
Hello, I have a question about TriangleMesh collision in PhysX. I created 4 PxShapes using PxTriangleMesh for displacement. This shapes have same y-value. In other words, The thickness of this shape is 0.
When I created dynamic prop that is created using PxConvexShape, it fell down ignoring triangle meshes Of course, I could see that onContact function is called. However, convex meshes surrounding the world is well handled collision process. What should I do to solve this problem?

This is screenshot.
![image](https://user-images.githubusercontent.com/5622661/63251173-25717e80-c2a8-11e9-83d6-244b2c14c988.png)

And this is PXD file.
[Problem.zip](https://github.com/NVIDIAGameWorks/PhysX/files/3514896/Problem.zip)

**Comment by Pierre-Terdiman** [comment]
(FWIW we had a thread about this on Twitter and it seems to be fixed now - https://twitter.com/utilforever/status/1163350180692815873?s=20)

**Comment by utilForever** [comment]
@Pierre-Terdiman Thanks! 🎆
