### ISSUE TITLE
Is it possible to add/remove shapes from actor using PxBVHStructure?

### ISSUE THREAD

**Issue by Zeblote** [NVIDIAGameWorks/PhysX#169]
Assume I have an actor that contains 10000 shapes and was initialized with a PxBVHStructure. I now want to add another shape to this actor.

Is using the normal attachShape / detachShape methods the correct way to do that while keeping the scene query in actor-centric mode? As in, it will update the compound pruner only, and *not* trigger a rebuild of the main one?

**Comment by AlesBorovicka** [comment]
Hi,
 yes that is correct, you can use the regular attach/detachShape it will add the shape into the compound pruner only. The rebuild of the main tree should not be triggered. The PxBVHStructure data are used only during the create time, then internally incremental AABB tree is used. So if shapes are added/removed during simulation the tree does remove/add objects accordingly. 

Regards,
Ales

**Comment by Zeblote** [comment]
Thanks! That's great to know.
