### ISSUE TITLE
CMAKE install script not copying include/cudamanager

### ISSUE THREAD

**Issue by al2950** [NVIDIAGameWorks/PhysX#17]
Hi

All public headers are copied over to the install directory **except** the include/cudamanager directory which means you get compile errors when using PhysX 4 CMAKE 'install' directory. 

Happy Christmas :)

**Comment by AlesBorovicka** [comment]
Hi,
 I see, yes this is not correct, we will fix this in next update, thanks for the report.
Regards,
Ales

**Comment by AlesBorovicka** [comment]
Fixed, should be in next patch update.
