### ISSUE TITLE
Cross compile for linux on windows

### ISSUE THREAD

**Issue by Zeblote** [NVIDIAGameWorks/PhysX#186]
Is it possible to build linux libs on windows? I noticed various hints suggesting this is possible, such as these lines here in `cmake_generate_projects.py`:
```
winPresetFilter = ['win','uwp','ps4','switch','xboxone','android','crosscompile']
```
```
elif self.targetPlatform == 'linux':
    [...]
    if self.compiler == 'clang-crosscompile':
```
However, the `crosscompile` preset doesn't exist in the public folder. Am I missing something simple?

**Comment by AlesBorovicka** [comment]
Yes, we dont include the linux-crosscompile preset. The preset could look like this:
linux-crosscompile.xml:
`
<preset name="linux-crosscompile" comment="Linux cross compilation preset, without GPU support">
  <platform targetPlatform="linux" compiler="clang-crosscompile" />
  <CMakeSwitches>
    <cmakeSwitch name="PX_GENERATE_STATIC_LIBRARIES" value="True" comment="Generate static libraries" />
  </CMakeSwitches>
  <CMakeParams>
    <cmakeParam name="CMAKE_INSTALL_PREFIX" value="install/linux-crosscompile/PhysX" comment="Install path relative to PhysX SDK root" />
  </CMakeParams>
</preset>
`

But note, that linux cross compile toolchain will be used, it is located in the PhysX/extenals/cmakemodules/linux
`            if self.compiler == 'clang-crosscompile':
                outString = outString + ' -DCMAKE_TOOLCHAIN_FILE=' + \
                    os.environ['PM_CMakeModules_PATH'] + \
                    '/linux/LinuxCrossToolchain.x86_64-unknown-linux-gnu.cmake'
`
In the toolchain file you would have to set your cross compile directory, as we dont include that on github. See this line in LinuxCrossToolchain.x86_64-unknown-linux-gnu.cmake
`SET(LINUX_ROOT $ENV{PM_PACKAGES_ROOT}/clang-crosscompile/5.0.0/x86_64-unknown-linux-gnu)`

**Comment by Zeblote** [comment]
Thanks! That worked perfectly.
I used the cross compile toolchain that comes with unreal, and their bundled make to build the makefile.

Btw, even though it works fine, cmake 3.15 is printing a lot of deprecation warnings when generating that preset.
