### ISSUE TITLE
PVD vs. D6Joints

### ISSUE THREAD

**Issue by WWebber** [NVIDIAGameWorks/PhysX#188]
Is "PxD6Joint" supposed to work with the debugger?
I get a weird error from "createPvdInstance()" !?

**Comment by kstorey-nvidia** [comment]
Please make sure you have called PxInitExtensions and passed the pointer to your PVD instance. This call registers metadata related to all extension types, including PxD6Joint.

**Comment by WWebber** [comment]
oups.. forgot about it.. thx.. solved !
