### ISSUE TITLE
Build Samples for Linux

### ISSUE THREAD

**Issue by Guillaumebeuzeboc** [NVIDIAGameWorks/PhysX#19]
After generating the project I compiled Physx with `make all` (in compiler) and it seems that only snippets are compiled.
I tried to run `cmake`  on the `CMakeLists.txt` in `PhysX/physx/samples/compiler/cmake`
And I encounter this error:

```
CMake Error at CMakeLists.txt:39 (MESSAGE):
  Could not find


-- Configuring incomplete, errors occurred!
```

I found [this](https://github.com/NVIDIAGameWorks/PhysX-3.4/issues/82) so I am not sure if samples are supposed to run under Linux.

**Comment by ghost** [comment]
Samples are still Windows only I believe. The reason I think so is because there are no Linux project files in the cmake directory for samples: https://github.com/NVIDIAGameWorks/PhysX/tree/4.0/physx/samples/compiler/cmake
I'm actually installing Visual Studio right now just to try the samples. But if they use OpenGL like in the snippets, I could try porting them.

It would be interesting to know why the snippets are Windows only though, maybe a Nvidia dev can help?

**Comment by Guillaumebeuzeboc** [comment]
That would be very interesting to have these samples running on Linux because the SDK User's guide is referring a lot to the samples. That would also be a really good starting point for any Linux project (regarding the CMakeLists.txt for example)

**Comment by ghost** [comment]
> That would be very interesting to have these samples running on Linux because the SDK User's guide is referring a lot to the samples. That would also be a really good starting point for any Linux project (regarding the CMakeLists.txt for example)

Yes, exactly. Although, I do think PhysX is using CMake in a kinda weird way, requiring Python to work. But it would definitely provide a starting point for sure!

**Comment by AlesBorovicka** [comment]
Hi,
 yes, we do not ship samples on linux. Our plan is to replace then in the future with something else. The current samples are too heavy to explore and do not provide much benefit. Unfortunately you are right our manual does mention them in some places. We need to address the manual for sure, the recommended way to explore the physx code in runtime should be the snippets. 
Anyway we have the samples necessary projects working internally on linux, so if there is interest, we should be enable to provide samples on linux in next update. 
Regards,
Ales
