### ISSUE TITLE
Build Failed with latest version of Physx and Xcode 

### ISSUE THREAD

**Issue by evandarcy** [NVIDIAGameWorks/PhysX#194]
Hi,

I cloned the repo today and have been trying to build Physx from the command line using `xcodebuild -project PhysXSDK.xcodeproj -alltargets -configuration debug`

When I run the command I am greeted with the following error message.

<img width="565" alt="Screenshot 2019-10-03 at 19 13 30" src="https://user-images.githubusercontent.com/31148326/66152846-413fa280-e612-11e9-89c0-5e73502a8f42.png">

I am hoping somebody has run into similar issues because I am at a loss for now unfortunately. I'm using OSX on Mojave.

**Comment by AlesBorovicka** [comment]
Hi,
 there was a merge request that disabled this warning:
https://github.com/NVIDIAGameWorks/PhysX/pull/185

**Comment by evandarcy** [comment]
Thanks for the reply. I cloned the repo just a few hours ago and got that error. Is that merge request on a separate branch or has it been merged with the master branch?

**Comment by AlesBorovicka** [comment]
Its merged into our main line, but has not yet been released, so I suggest to apply that fix locally.

**Comment by evandarcy** [comment]
Yep, sorted, thanks!
