### ISSUE TITLE
Fix for high CPU usage in samples. Busy-waiting loops.

### ISSUE THREAD

**Issue by datgame** [NVIDIAGameWorks/PhysX#2]
1) Change vsync = false; in RendererDesc.cpp to true.
2) Add Ps::Thread::sleep(1); on line 97 in SampleMain.cpp
This brings down 2 busy-waiting cores, some 28% cpu usage on my pc, down to 2%.
No more noisy fans when trying out the demos.

**Comment by amoravanszky** [comment]
Thanks, I added this in our internal mainline, it will be part of the next github update.
