### ISSUE TITLE
Can I disable AggAggPairs between static actors?

### ISSUE THREAD

**Issue by Zeblote** [NVIDIAGameWorks/PhysX#205]
In a scene with ~1000 compound PxRigidStatic (each in their own aggregate) that contain ~1500000 shapes, adding another shape to one of them causes this to show up in the profile:

![image](https://user-images.githubusercontent.com/6764788/67225471-97467f80-f433-11e9-9ef2-7474884e1c8e.png)

Now since these are all static I will never care about any pairs between them, is it possible to remove these tasks? Maybe a flag I missed?

**Comment by Pierre-Terdiman** [comment]
It is not possible in current PhysX version. You did not miss a flag.

Improved aggregate filtering (and indeed, a way to "remove these tasks") has already been implemented for the next PhysX version. If needed, we might be able to back-port the change to make it appear earlier on GitHub.

**Comment by Zeblote** [comment]
Sounds great, I will wait for the next version then :)

**Comment by Zeblote** [comment]
I forgot to ask, do you have a rough estimate when this version will be ready? Like, is it going to be a few weeks, or 3 months, or more?
