### ISSUE TITLE
PxCreateCooking

### ISSUE THREAD

**Issue by WWebber** [NVIDIAGameWorks/PhysX#207]
At PxCreateCooking() I read foll. comment: "To use cooking in standalone mode, create an instance of the Foundation object with PxCreateCookingFoundation"
But where is 'PxCreateCookingFoundation' ?

**Comment by PierreTerdiman** [comment]
Thank you, this was a simple typo (the correct name is of course just "PxCreateFoundation"). This has been fixed in our trunks.
