### ISSUE TITLE
URDF import pipeline

### ISSUE THREAD

**Issue by christoph-jaehne** [NVIDIAGameWorks/PhysX#23]
Hello,
I would like to use PhysX4.0 for simulating robots and to evaluate e.g. different kinematics. Therefore a pipeline for importing URDF-described robots as `PxArticulationReducedCoordinate` for simulation in generalized coordinates would be extremely valuable.
Are there any plans for adding URDF support?

**Comment by amoravanszky** [comment]
Hi,

I like to avoid making specific promises of upcoming features, but we are aware of this need and are working on providing you with solutions. :)

**Comment by letrend** [comment]
any updates on that? really looking forward to simulate our robots with this...
