### ISSUE TITLE
Compile physx4 in a Linux environment

### ISSUE THREAD

**Issue by yumianhuli2** [NVIDIAGameWorks/PhysX#233]
How can I compile physx4 in Linux？Have a tutorial?Thank you！

**Comment by AlesBorovicka** [comment]
Hi,
 there should be a linux readme file with a list of prerequisites and how to:
[https://github.com/NVIDIAGameWorks/PhysX/blob/4.1/physx/documentation/platformreadme/linux/readme_linux.html](url)

**Comment by yumianhuli2** [comment]
> Hi,
> there should be a linux readme file with a list of prerequisites and how to:
> [https://github.com/NVIDIAGameWorks/PhysX/blob/4.1/physx/documentation/platformreadme/linux/readme_linux.html](url)
HI！
I've compiled phyx from the readme, but I want to know where the output is？
For example I want to run samplevehicle in the examples how can I do that?

**Comment by AlesBorovicka** [comment]
The binaries should be in bin/linux.clang (release/debug/etc..) directory, run the samples executable and select vehicle sample.

**Comment by yumianhuli2** [comment]
> The binaries should be in bin/linux.clang (release/debug/etc..) directory, run the samples executable and select vehicle sample.

ok,I found it in the bin/linux.clang/debug folder and run the vehicle sample.1、But How can I find the source code corresponding to these examples？
![Screenshot from 2020-01-07 16-52-01](https://user-images.githubusercontent.com/39210837/71881823-106d8d00-316e-11ea-9763-3894855a6f69.png)

2 How can I run this(samplevehicle) on linux?Is there a detailed tutorial on this？
![Screenshot from 2020-01-07 16-44-34](https://user-images.githubusercontent.com/39210837/71881316-08f9b400-316d-11ea-8357-66d4cd8b0009.png)

**Comment by AlesBorovicka** [comment]
1) source code for snippets is in snippets folder
2) There should be also Samples_64 executable, which you can run and in the app you can select that vehicle sample.
