### ISSUE TITLE
mHullDataHullVertices

### ISSUE THREAD

**Issue by numega** [NVIDIAGameWorks/PhysX#235]
mHullDataHullVertices is allocated with the incorrect size in ConvexHullBuilder::init() and ConvexPolygonsBuilder::computeHullPolygons(). Currently, it's:

mHullDataHullVertices			= reinterpret_cast<PxVec3*>(PX_ALLOC(sizeof(PxVec3) * mHull->mNbHullVertices + 1, "PxVec3"));

But should be:

mHullDataHullVertices			= reinterpret_cast<PxVec3*>(PX_ALLOC(sizeof(PxVec3) * (mHull->mNbHullVertices + 1), "PxVec3"));

**Comment by AlesBorovicka** [comment]
Yes, looks like a bug, will change it on our code base. Thanks!
