### ISSUE TITLE
Character controller always calls filter callback whether PxQueryFlag::ePREFILTER flag is set.

### ISSUE THREAD

**Issue by ghost** [NVIDIAGameWorks/PhysX#244]
Hi,

At the 2020th line of PhysX/physx/source/physxcharacterkinematic/src/CctCharacterController.cpp, 
```cpp
if(filters.mFilterCallback && (filters.mFilterFlags | PxQueryFlag::ePREFILTER))
```
the result of the latter half is always true, so if filter callback is assigned, it will be called whether filter flags is set properly.

**Comment by Pierre-Terdiman** [comment]
I think you're right, this | should be an &.
