### ISSUE TITLE
generate_projects.bat does not generate a project and shows nothing

### ISSUE THREAD

**Issue by mrjbom** [NVIDIAGameWorks/PhysX#271]
Hello.
My cmake and python versions fit the requirements. When I run build_projects.bat with some argument, I don't get anything except exit /b 0. After that, I press Enter and nothing happens.
What is the problem?

![image](https://user-images.githubusercontent.com/37502620/77576175-c29f3000-6ee5-11ea-946c-ae5064261e59.png)

Thanks.

**Comment by ayoub-belarbi** [comment]
Hi @mrjbom,
What you are facing is caused by the fact that the `generate_projects.bat` script couldn't find the Python executable. This is a well know issue and the workaround in #252 would fix the issue.
Thanks

**Comment by mrjbom** [comment]
Thank you. The problem is solved.
