### ISSUE TITLE
Question: Filter Shader (DynamicRigidbody & StaticRigidBody)

### ISSUE THREAD

**Issue by knela96** [NVIDIAGameWorks/PhysX#273]
I've been testing the filter shader with some colliders and rigidbodies, seems that if both colliders have a dynamic rigidbody the filtershader gives me the pxFilterData of both, but if one of them is static it gives me only 1 pxFilterData and in the next iteration the other. Is it possible to receive both of them as it does when both are dynamic?

**Comment by lucho1** [comment]
I'm working with @knela96, and this problem was solved by first creating the shape, then calling shape->setSimulationFilterData() and finally creating the rigidbody
