### ISSUE TITLE
How to implement a robot in PhysX for collision detection?

### ISSUE THREAD

**Issue by AlexBo96** [NVIDIAGameWorks/PhysX#277]
Hi,

i have a question about PhysX.
How can a robot / robot gripper / CAD model be implemented for collsion detection in PhysX? Are there any documentations available?
I am new to the subject and have a lot to struggle with it.

Thanks for your help.

**Comment by Levi-Armstrong** [comment]
Are you needing Physics or just collision detection?

**Comment by AlexBo96** [comment]
Actually I need collision detection, but I want to realize it with PhysX.

**Comment by Levi-Armstrong** [comment]
I would take a look at #264

**Comment by AlexBo96** [comment]
Thanks for the hint. I'll try.
