### ISSUE TITLE
Compile ios64, the static lib's size is too large

### ISSUE THREAD

**Issue by aiplay** [NVIDIAGameWorks/PhysX#28]
After I compiled PhysX SDK with xcode, the libPhysX_static_64.a is _221Mb_.
When set the **Generate Debuy Symbols** is **False**, the generate static lib is _186Mb_, but still too large for our git project.
So, how can I to reduce the size of libPhysX_static_64.a ??

**Comment by AlesBorovicka** [comment]
You can compile only architecture that you need. It does contain now three architectures, you can select to compile only target architecture, so the size will be roughly a third.

**Comment by aiplay** [comment]
Only use arm64 architechture, the  libPhysX_static_64.a  size is 61Mb, is it normal ?

**Comment by AlesBorovicka** [comment]
Without the debug symbols it could be

**Comment by zhongfugao** [comment]
I met this issue as well, any updates on it?
