### ISSUE TITLE
How to use checked configuration of PhysX when my project uses debug configuration

### ISSUE THREAD

**Issue by climber03** [NVIDIAGameWorks/PhysX#29]
Hi folks, the PhysX documentation says "We strongly recommend that you use the checked build as the primary configuration for day-to-day development and QA.". My project uses the runtime library /MDd (because it's in debug configuration) but the checked configuration of PhysX uses /MD. This causes a linker error (LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in xxx.obj). A possible solution is to use the debug configuration of PhysX, which also uses the /MDd runtime library, but i don't think thats the correct solution to this issue.

My project uses the following PhysX libs:
- PhysX_64.lib
- PhysXCommon_64.lib
- PhysXCooking_64.lib
- PhysXFoundation_64.lib
- PhysXExtensions_static_64.lib
- PhysXPvdSDK_static_64.lib
- FastXml_static_64.lib

Are there any ideas how to solve this issue?

Thanks,
Michael

**Comment by AlesBorovicka** [comment]
Hi,
 For your debug configuration where you use debug CRT, there is not much you can do, you would have to link against debug CRT PhysX libraries, which is debug configuration. However it is quite common to create another development configuration, that does use for example checked PhysX while the application code can still use unoptimized build. 
Regards,
Ales
