### ISSUE TITLE
How do I combine several shapes into one?

### ISSUE THREAD

**Issue by mrjbom** [NVIDIAGameWorks/PhysX#290]
Hi.
I'm trying to create a non-convex dynamic body. To do this, I split a non-convex shape into several convex ones using V-HACD.
And I have a question:
how can I create and combine several convex shapes into one and calculate the center of mass for this "single" shape?

**Comment by Levi-Armstrong** [comment]
I am not sure if this is what you are looking for, but an actor allows you attach multiple shapes using `attachShape`. You can also define a separate BVH structure for the attached shapes when you add the actor to the scene or to an aggregate.

**Comment by mrjbom** [comment]
Thank you.
