### ISSUE TITLE
Physx 5.0 +DEM ( help wanted )

### ISSUE THREAD

**Issue by ghost** [NVIDIAGameWorks/PhysX#338]
https://gpuopen.com/femfx/ 

https://www.techradar.com/news/nvidia-reveals-physx-50-but-amds-explosive-femfx-demos-already-stole-its-physics-thunder - Wasn't code for Physx 5 meant to be released? Even if we sort it out ourselves?

Seems to be dead and only see 4/4.1 here

**Comment by alanjfs** [comment]
Haha, what is this? xD

**Comment by ghost** [comment]
a question, i dont know where else to find the answer

**Comment by alanjfs** [comment]
Looks like a question, rolled into some negative assertions, a competing product and a clickbait news article.

Perhaps the question you meant to ask was simply "When is PhysX 5.0 released?". To which I would also very much like to know the answer, because it looks amazing! Huge props to the team on this one.

**Comment by ghost** [comment]
Yeah, sorry I was just confused about why nobody talks about it now. Wasn't it 2020 release?

**Comment by kstorey-nvidia** [comment]
PhysX 5 is still in development and has not been released yet. It is, however, in use in several NVIDIA projects. This has been discussed in another issue here:

https://github.com/NVIDIAGameWorks/PhysX/issues/309#issuecomment-665751081

**Comment by ghost** [comment]
Thank you so much for the response! @kstorey-nvidia 

Sorry if I came off wrong in the other message 😅 I didn't mean offense, honest

**Comment by ghost** [comment]
Closed due to not being able to know anything on the matter till official release

**Comment by Nulled-Out** [comment]
Would this need re-opening to ask about any maximum timeframe? 🤔
