### ISSUE TITLE
PxBatchQuery flagged as deprecated but still used in Vehicle SDK

### ISSUE THREAD

**Issue by rouxfrancis** [NVIDIAGameWorks/PhysX#341]
PxBatchQuery is flagged as deprecated but is still used in Vehicle SDK by PxVehicleSuspensionRaycasts and PxVehicleSuspensionSweeps.

I would just like to have an idea of the evolution that these methods will take in PhysX 5.

Thanks

**Comment by gyeomannvidia** [comment]
We've amended this internally.  The api for PxVehicleSuspensionRaycasts and PxVehicleSuspensionSweeps has changed very slightly as a consequence but it is a trivial change.

**Comment by PathogenDavid** [comment]
@gyeomannvidia

> We've amended this internally.

I know the focus is on PhysX 5 these days, but is there a chance these changes could be synchronized to this repo?
