### ISSUE TITLE
Joint position encoding for articulations

### ISSUE THREAD

**Issue by cfognom** [NVIDIAGameWorks/PhysX#344]
If I have a 3 dof reduced coordinate articulation joint, what is the encoding of the joint positions? I'm using PhysX though Unity and have tested all 6 possible Tait–Bryan rotation orderings to reproduce the joint positions of the articulation, but neither of them were accurate. I also found an earlier post about this issue, saying that the ordering was (ZYX format, Tait-bryan) but according to my tests it is not. Why is this not specified in the docs?

**Comment by lasagnaphil** [comment]
The spherical joint format abruptly changed in an update in 4.1.1. The joint rotations are now embedded in a rotation vector (axis-angle representation). I guess this change was necessary to avoid singularities in the previous Euler angle representation, but it was quite frustrating that this wasn't anywhere in the docs or the changelogs.

**Comment by cfognom** [comment]
Ah, yes axis angle accurately reproduces their rotations. Thank you!
