### ISSUE TITLE
SnippetContactReportCCD

### ISSUE THREAD

**Issue by wangdahao** [NVIDIAGameWorks/PhysX#348]
After running my “SnippetContactReportCCD” snippet, the ball is still, I don't know how to make it move！

**Comment by Pierre-Terdiman** [comment]
I didn't write that snippet but I'm pretty sure it's by design. It captures & shows what happens in a single frame using CCD, displaying the CCD contacts, etc.

**Comment by PierreTerdiman** [comment]
Closing for now, please re-open if you still think there is a problem.
