### ISSUE TITLE
[PhysX 4.1] Enable joints visualization for PVD

### ISSUE THREAD

**Issue by elderkeltir** [NVIDIAGameWorks/PhysX#357]
Hello!
I have an issue with joints on ragdoll. In some cases it doesn't stop simulation after rag doll activation:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/1653123/97551048-24bf9680-19db-11eb-9119-4ef42c891608.gif)

So I wanted make use of PVD to help me understand what is the issue's root cause. I enabled PVD like this:
```
// SDK
_pvd = PxCreatePvd(*_foundation);
_transport = PxDefaultPvdFileTransportCreate("d:/pvd");
_pvd->connect(*_transport, PxPvdInstrumentationFlag::eDEBUG);
_sdk	= PxCreatePhysics(PX_PHYSICS_VERSION, *_foundation, tol, true, _pvd);
PxInitExtensions(*_sdk, _pvd); // checking result here

//SCENE
auto pvd = _scene->getScenePvdClient();
pvd->setScenePvdFlags(PxPvdSceneFlag::eTRANSMIT_CONSTRAINTS | PxPvdSceneFlag::eTRANSMIT_SCENEQUERIES | PxPvdSceneFlag::eTRANSMIT_CONTACTS);

_scene->setVisualizationParameter(PxVisualizationParameter::eSCALE, 10.f);
_scene->setVisualizationParameter(PxVisualizationParameter::eJOINT_LOCAL_FRAMES, 1.0f);
_scene->setVisualizationParameter(PxVisualizationParameter::eJOINT_LIMITS, 1.0f);
 _scene->setVisualizationParameter(PxVisualizationParameter::eACTOR_AXES, 1.0f);

//ACTORS
PxActorFlags aflags = PxActorFlags(0);
aflags |= PxActorFlag::eVISUALIZATION;
_actor->setActorFlags(aflags);

//D6 JOINTS
joint.setConstraintFlag(PxConstraintFlag::eVISUALIZATION, true);
```

Unfortunately I can't see any joint related information in my file. 
![image](https://user-images.githubusercontent.com/1653123/97552572-16727a00-19dd-11eb-8206-fc487308e39a.png)

I tried everything I was able to find in documentation, still no luck.
Can you please assist with joints visualization.

**Comment by Esentiel** [comment]
It seems, there is some problem with soft limits and low rate of simulate. I wasn't able to reproduce this behavior when switched joints to hard limit or keep simulation rate at 120+
Also I found the function where we set motion parameters for joint based on stiffness, damping AND dt: **https://github.com/NVIDIAGameWorks/PhysX/blob/4.1/physx/source/lowleveldynamics/src/DySolverConstraint1D.h#L165**
We have stiffness equals to 1000(it was reproduced with 100 stiffness as well) and damping equals to 50.

**Comment by elderkeltir** [comment]
Hello,

I did debug a bit and found out that the code is executed:
https://github.com/NVIDIAGameWorks/PhysX/blob/4.1/physx/source/physx/src/buffering/ScbScenePvdClient.cpp#L834
Which should basically mean that PVD and joint visualization was enabled.

Same for contacts, this line of code was executed, which means that data for contacts were send to PVD stream
https://github.com/NVIDIAGameWorks/PhysX/blob/4.1/physx/source/physx/src/buffering/ScbScenePvdClient.cpp#L872

I've tried both streaming to file and via socket. No difference at all.

Any ideas?

**Comment by elderkeltir** [comment]
Oops, guess I was looking for joints/contacts information in the wrong place. I found info on the right side panel
![image](https://user-images.githubusercontent.com/1653123/99273589-e6770380-2831-11eb-9bf3-d49021eb72d9.png)
