### ISSUE TITLE
Custom joints

### ISSUE THREAD

**Issue by YashaAkimov** [NVIDIAGameWorks/PhysX#362]
for example: i want to create cam, wich transforming rotary motion into linear motion. 
![Cam-disc-3_frontview_animated](https://user-images.githubusercontent.com/22431570/99518784-7b9d0800-29aa-11eb-84a8-6b7b0c205d95.gif)
its wery easy only if i need transfer motion from bottom to top, just using sweeps. But its not consider forces, applying to top side of cam.
another way is implement full mechanism in simulation world, but I think it wold have poor performance, because its need to calculate collision between two or more high poly objects and solve at least 3 standart joints instead of solving one custom joint.
So it's possible to create joint based on custom math model ?

**Comment by kstorey-nvidia** [comment]
Yes, it is. Take a look at "SnippetCustomJoint" in the PhysX SDK. That snippet demonstrates creating a pulley joint as a custom joint.

**Comment by YashaAkimov** [comment]
Many thanks.
