### ISSUE TITLE
PxConvexFlag::eINFLATE_CONVEX is missing

### ISSUE THREAD

**Issue by webhaikal** [NVIDIAGameWorks/PhysX#37]
As per mentioned in the title, the following flag `eINFLATE_CONVEX` is missing inside `Includes/cooking/PxConvexMeshDesc.h` but removal is not mentioned inside release notes. Has the flag been moved?

**Comment by AlesBorovicka** [comment]
Hi,
 eINFLATE_COVEX has been marked as deprecated in 3.4 and was removed in 4.0 together with the legacy inflation based convex hull cooking.

Regards,
Ales

**Comment by webhaikal** [comment]
Ok thanks for the reply. So I no longer have to call the flag since it uses inflation in all cases?

**Comment by AlesBorovicka** [comment]
eINFLATE_COVEX convex was used together with the legacy inflation based algorithm, the current algorithm does not inflate the convex. The produced convex does contain only a subset of the input points.
Should you need to collide a bit further from the convex you can try to tweak PxShape::setContactOffset and PxShape::setRestOffset.
