### ISSUE TITLE
std::remove_if doesn't handle return value, generates nodiscard warning

### ISSUE THREAD

**Issue by dbechrd** [NVIDIAGameWorks/PhysX#392]
File: `physx\samples\sampleframework\renderer\src\d3d11\D3D11RendererMemoryMacros.h`
Warning: `discarding return value of function with 'nodiscard' attribute`

The code which generates the warning:
```cpp
template<class T>
PX_INLINE void deleteAll( T& t ) { std::remove_if(t.begin(), t.end(), deleteAndReturnTrue<typename T::value_type>); };

template<class T>
PX_INLINE void dxSafeReleaseAll( T& t ) { std::remove_if(t.begin(), t.end(), dxReleaseAndReturnTrue<typename T::value_type>); };
```

**Comment by PierreTerdiman** [comment]
There was a pull request with a fix for these that I just merged to our trunks.
