### ISSUE TITLE
getName() and setName() don't have default implementations

### ISSUE THREAD

**Issue by morphogencc** [NVIDIAGameWorks/PhysX#395]
In `PxActor.h`, there's a virtual function for `setName(const char* name)` and `getName()` but these are not defined.

It looks like 

In the samples `samplelargeworld` and `samplebridges`, there is use of `setName()` and `getName()`, but no corresponding function definition.  Is this leftover from a previous version of PhysX, or is there supposed to be a default implementation that is usable by these samples?

**Comment by kstorey-nvidia** [comment]
The definitions are in the NpActorTemplate class.

**Comment by PierreTerdiman** [comment]
Closing this, since it seems to work as expected as far as I can tell. Please re-open otherwise.
