### ISSUE TITLE
There is a mistake of contact solver in PhysX 3.4.2

### ISSUE THREAD

**Issue by pkusilence** [NVIDIAGameWorks/PhysX#397]
In DyContactPrep4.cpp , line 535:

				Vec4V unitResponse = V4MulAdd(invMass0D0, angDom0, dotDelAngVel0);

should be replaced by 

				Vec4V unitResponse = V4MulAdd(dotDelAngVel0, angDom0, invMass0D0);

in the original version, the invMass is scaled by angDom0, which is intended to scale the invInertia

**Comment by kstorey-nvidia** [comment]
Thanks. You are absolutely right. This is a typo. I have updated our development trunk. Thanks
