### ISSUE TITLE
which function is used to "generate a convex mesh from an arbitrary input mesh" ?

### ISSUE THREAD

**Issue by Timkeeper2018** [NVIDIAGameWorks/PhysX#402]
Hi.
I see some issue say that PhysX provides functionality to generate a convex mesh from an arbitrary input mesh. 
Does that mean that even if my mesh is a triangle mesh, I can input vertices into that function to create a convex mesh? If so, what is that function?
Thanks

**Comment by AlesBorovicka** [comment]
Hi,
 You should be able to create a convex mesh using the PxCooking interface, namely create/cookConvexMesh function.
See snippet convex mesh create [https://github.com/NVIDIAGameWorks/PhysX/blob/4.1/physx/snippets/snippetconvexmeshcreate/SnippetConvexMeshCreate.cpp](https://github.com/NVIDIAGameWorks/PhysX/blob/4.1/physx/snippets/snippetconvexmeshcreate/SnippetConvexMeshCreate.cpp)
