### ISSUE TITLE
How to create constraints for two intersecting objects in a simple way

### ISSUE THREAD

**Issue by Timkeeper2018** [NVIDIAGameWorks/PhysX#405]
Hi,
  In order to simulate the breaking effect of objects, I tried to refer to "SnippetJoint" to make a simple demo: connect two intersecting objects using joints, and they will break under the action of force.
  Because I only have two (PxRigidDynamic*), I also need to provide the relative position between the two objects when using PxJoint. So I am considering whether there is a simpler way to achieve the constraint effect, such as using PxConstrain. But I don't know how to use PxConstrain to create constraints, how to use two PxRigidDynamic* to detect whether objects intersect. . . . . . (I'm too food)
  Thanks in advance.
The code part is as follows:
`
if (1)
	{
		PxRigidDynamic* dynamic1 = createDynamic(PxTransform(PxVec3(0, 1.0, 0)), PxBoxGeometry(1.0,1.0,1.0), PxVec3(0, 0, 0));
		PxRigidDynamic* dynamic2 =createDynamic(PxTransform(PxVec3(0, 2.0, 0)), PxBoxGeometry(1.0, 1.0, 1.0), PxVec3(0, 0, 0));
		PxBoxGeometry asd = PxBoxGeometry(dynamic1->getWorldBounds().getExtents());
		PxTransform dd = dynamic1->getGlobalPose();
		
		PxBoxGeometry asd2 = PxBoxGeometry(dynamic2->getWorldBounds().getExtents());
		PxTransform dd2 = dynamic2->getGlobalPose();

		bool hahaha = PxGeometryQuery::overlap(asd, dd, asd2, dd2);
		if (hahaha) 
		{
			PxVec3 t0 = dd.p;
			PxVec3 t1 = dd2.p;
			PxTransform T0 = PxTransform((t1 - t0)/2);
			PxTransform T1 = PxTransform((t0 - t1) / 2);
			PxSphericalJoint* j = PxSphericalJointCreate(*gPhysics, dynamic1, T0, dynamic2, T1);

			j->setBreakForce(1000, 100000);
			j->setConstraintFlag(PxConstraintFlag::eDRIVE_LIMITS_ARE_FORCES, true);
			j->setConstraintFlag(PxConstraintFlag::eDISABLE_PREPROCESSING, true);
		}

	}
`

**Comment by kstorey-nvidia** [comment]
It is easier to use one of our pre-defined if you want to use existing joint functionality. The PxConstraint is then created through creating a joint. The PxConstraint takes the joint shaders and data that is owned by the PxJoint and feeds that through to the PhysX solver to define the constraints on the rigid bodies.

If you want to create a PxConstraint yourself directly, you would need to provide joint shaders to create the Jacobians for the constraints.

**Comment by Timkeeper2018** [comment]
thanks
