### ISSUE TITLE
Misleading image in guide for sweep

### ISSUE THREAD

**Issue by MaxLap** [NVIDIAGameWorks/PhysX#406]
Hello,

At https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/guide/Manual/GeometryQueries.html, there is this image explaining what a sweep is:

![image](https://user-images.githubusercontent.com/894561/111904605-22a7b400-8a1e-11eb-8dd6-4828d83ba307.png)

The "hit distance" is wrong. It should be from the middle of the right shape to the middle of its "shadow" on the left. 

I had been using unnecessary hacks, such as doing a reverse RayCast, to figure out which part of the shape touched, because this image mislead me. At one point, I just though that this hit distance was so useless it had to be a mistake in the image. And after testing, the mistake is indeed in the image.

I'm sure I'm not alone in this situation. Could someone fix the image please? Thank you

Link to the image in this repo: https://github.com/NVIDIAGameWorks/PhysX/blob/4.1/physx/documentation/PhysXGuide/_images/GeomQuerySweep.png

**Comment by alanjfs** [comment]
Did some quick surgery to better understand what it was *supposed* to look like, is this what you mean?

![image](https://user-images.githubusercontent.com/47274066/112713650-40699300-8ece-11eb-9168-1a5728058b4c.png)

**Comment by MaxLap** [comment]
Yes, this looks perfect!

**Comment by PierreTerdiman** [comment]
Thank you, this image is indeed incorrect. Will fix.

**Comment by kstorey-nvidia** [comment]
This should be corrected now
