### ISSUE TITLE
Failed to build snippets

### ISSUE THREAD

**Issue by yongyili** [NVIDIAGameWorks/PhysX#408]
Platform: Windows 10 20H2
Steps:
1. Clone the branch 4.1 of Physx ;
2. Cd into 'PhysX\physx' and run generate_projects.bat ; 
3. Cd into PhysX\physx\snippets\compiler\cmake and run 'cmake .'
4. An error is reported:
```shell
CMake Error at CMakeLists.txt:38 (MESSAGE):
  Could not find
```

**Comment by ayoub-belarbi** [comment]
Hi, 

Please follow the instructions here for Windows: https://github.com/NVIDIAGameWorks/PhysX/blob/4.1/physx/documentation/platformreadme/windows/readme_windows.html

Best regards
Ayoub

**Comment by yongyili** [comment]
Hi,
Thanks  a lot for your help.
So, there is no need to run cmake again in the snippets directory.
