### ISSUE TITLE
Math classes

### ISSUE THREAD

**Issue by M-S-M-A-S** [NVIDIAGameWorks/PhysX#412]
The [documentation ](https://gameworksdocs.nvidia.com/PhysX/4.1/documentation/physxguide/Manual/API.html) mentioned math classes in foundation library such as PxVec4, PxMat44 

but they are not implemented with intrinsics, where can I find the ones implemented with intrinsics????

**Comment by kstorey-nvidia** [comment]
The PxVec4 etc. maths types do not use intrinsics and are mainly used as interface types.

Much of the low-level dynamics and collision code uses intrinsics where they can offer performance advantages. The underlying intrinsics are platform-specific. For example, the Windows-specific files are found here in the foundation code here:

https://github.com/NVIDIAGameWorks/PhysX/tree/4.1/physx/source/foundation/include/windows
https://github.com/NVIDIAGameWorks/PhysX/tree/4.1/physx/source/foundation/src/windows

**Comment by MouseAmaneCommits** [comment]
use glm
