### ISSUE TITLE
Porting PhysX to another platform

### ISSUE THREAD

**Issue by elderkeltir** [NVIDIAGameWorks/PhysX#414]
Hello!

PhysX doesn't support PS5(or BSD which should be close to PS5) and probably we will need to port it to PS5, can anyone involved in the project(or the one who was involved in the similar task) please assist in estimation: how much time will it take with any possible accuracy(days/weeks). I checked some of platform specific stuff that I faced to trying to compile sdk on BSD, and that didn't look to scary. On the other hand, I expect to find some pitfalls that I can't see now.

At the same time I have a pet project based on PhysX, and want to give it a try to compile SDK for BSD. Which might help us to get desired PS5 build.

Any feedback will be very helpful!

PS: I do not ask for any sensitive information at all, just some estimation or generic advices, I'm aware of Vendors NDA etc.

**Comment by Esentiel** [comment]
I found similar issue and answer in it.

**Comment by kstorey-nvidia** [comment]
If you send an email to physxlicensing@nvidia.com and can confirm that you are a signed up console developer, you should be able to get access to the platform-specific code and cmake configurations for consoles. Due to vendor NDAs etc., we can't provide those files freely on GitHub.
