### ISSUE TITLE
Damping of a Revolute Joint

### ISSUE THREAD

**Issue by HA1N** [NVIDIAGameWorks/PhysX#418]
Hello,

I’m currently testing the behavior of the “Articulation-Body” feature, which uses PhysX SDK 4.0 included in Unity3D.
To investigate the behavior of a revolute joint a simple test case was used. A single beam is connected to a immovable base structure (Cube) by a revolute joint. At a set time (0.1s) the target angle is changed to a new position and the displacement of the endpoint of the beam is tracked.

As a reference a similar test case was build in Matlab/Simulink. As shown in the figure the damping in Unity3D is significantly greater compared to the matlab results.

![Matlab_Unity_Comparison](https://user-images.githubusercontent.com/79192430/116849217-a4c6f300-abee-11eb-9b33-e3e340d85817.png)

Before further testing can take place it would require to know the reason where this difference comes from. Is there any simplification in PhysX that could cause this amplified damping effect?
Best regards,
Niklas

**Comment by preist-nvidia** [comment]
Hi Niklas, please see my reply on the forum: https://forums.developer.nvidia.com/t/damping-of-a-revolute-joint/176867
