### ISSUE TITLE
Speculative CCD & performance in large scenes

### ISSUE THREAD

**Issue by ikkah** [NVIDIAGameWorks/PhysX#42]
Hi,

I've been investigating some performance issues we have in large scenes (well over 10k rigid bodies). It seems that enabling speculative CCD on objects causes the objects to update contact distances via ScScene.preRigidBodyNarrowPhase even if they are sleeping. The contact distance update itself is rather expensive when many of the objects in the scene have speculative CCD enabled, but what's worse is that updating the contact distance causes BpSAP.updateWork to touch those objects as well.

Is there a reason why the contact distance is updated even for sleeping objects? To me it seems that it's only needed to inflate the contact distance when the object is moving. If the update is necessary, are there any other ideas for improving speculative CCD performance in large scenes?

**Comment by kstorey-nvidia** [comment]
Thanks for reporting this. You are absolutely right - only active objects should be processed in this code. I'll add a work item and it will be fixed soon.
