### ISSUE TITLE
physx::PxShape::setGeometry not working

### ISSUE THREAD

**Issue by TheDonsky** [NVIDIAGameWorks/PhysX#428]
Hello,
I tried to resize a box shape by calling setGeometry(), but neither the behavior, nor the debuggers (PVD and MSVS) shows any change. Do I need to have some specific configuration for it to work?
I'm attaching a screenshot from visual studio, highlighting the issue.

When I run the sample code below, 'old' always equals 'cur' and they both differ from 'desired'.
```
physx::PxBoxGeometry old;
bool gotOld = Shape()->getBoxGeometry(old);
physx::PxBoxGeometry desired = Geometry(newShape);
Shape()->setGeometry(desired);
physx::PxBoxGeometry cur;
bool gotCur = Shape()->getBoxGeometry(cur);
```

![debug](https://user-images.githubusercontent.com/19620595/120358731-e646dd00-c317-11eb-9fdb-5bceffbd5750.jpg)

**Comment by kstorey-nvidia** [comment]
Are you using shared shapes? It's illegal to change the geometry on a shared shape once it is attached to an actor. You should get some debug error messages telling you what you did that isn't allowed.

**Comment by TheDonsky** [comment]
Thanks, I was not aware of the restriction and logs were not visible when I first stumbled across the issue for some reason and did not think of looking when I switched to the debug build..
