### ISSUE TITLE
PhysX rotates dynamic objects by 180 degrees.

### ISSUE THREAD

**Issue by IceLuna** [NVIDIAGameWorks/PhysX#474]
Hi. 
The simulation runs fine if I run it on my PC (i5-9400f, GTX 1660 Ti) but when I run the same simulation on my laptop (i5-8250u, MX150) on the very first frame dynamic objects get rotated by 180 degrees around Z axis (points into the screen). It happens even if I lock rotation.

Before running the simulation
![image](https://user-images.githubusercontent.com/48557794/133682219-bd7492d1-2d88-4910-8577-63fc97a5d71c.png)
After
![image](https://user-images.githubusercontent.com/48557794/133682192-c0b11fea-2005-4e04-b92f-d5af37589f8d.png)

As you can see, the box and the barrel on the right are flipped.
Any ideas why is that happening?

**Comment by kstorey-nvidia** [comment]
Can you please provide a PVD capture so we can confirm that the transforms are definitely different? Are you using GPU or CPU simulation?

**Comment by IceLuna** [comment]
I'm using CPU simulation. PVD shows that rotation is 0...
![image](https://user-images.githubusercontent.com/48557794/133830532-f6e500b2-0840-402f-9bb4-abe73b356110.png)

Apparently, it wasn't PhysX problem. For some reason, glm::eulerAngles returns 180 sometimes... 
![image](https://user-images.githubusercontent.com/48557794/133832074-4d79ce4b-7db3-43ed-a758-3beec5c0a1c3.png)

Thanks for the help!
