### ISSUE TITLE
Porting PhysX to FreeBSD

### ISSUE THREAD

**Issue by elderkeltir** [NVIDIAGameWorks/PhysX#479]
Hello!

I recently moved to FreeBSD on my home desktop and to be able to work on my pet project(that depends on PhysX) I ported PhysX to FreeBSD. I made patch that contains necessary changes to compile PhysX library on FreeBSD. Still I didn't do anything about Samples and Snippets, simply because I don't use it.
Now I think if you guys are interested in extending portability for PhysX 4 and maintaining FreeBSD support, I can port samples, snippets as well and submit a proper pull request with changes.

Cheers

**Comment by Martinfx** [comment]
some progress  ? is year 2024

**Comment by preist-nvidia** [comment]
Hi both - we will not update supported platforms for PhysX 4 anymore, and for PhysX 5 we are currently not planning to expand the supported platforms.
