### ISSUE TITLE
amd gpu

### ISSUE THREAD

**Issue by manotroll** [NVIDIAGameWorks/PhysX#5]
now that it has become "open" does it support acceleration also on amd boards as it was in the past with mods?

**Comment by sheikh-nv** [comment]
Hi, we currently only support GPU acceleration through CUDA with our PhysXGPU binaries. More info on our Windows requirements here: 
http://gameworksdocs.nvidia.com/PhysX/4.0/documentation/platformreadme/windows/readme_windows.html

**Comment by manotroll** [comment]
so there is nothing free

**Comment by Zogrim** [comment]
I think you have a misconception here. GPU codepath is written on CUDA, it can't magically run on AMD GPU because sources are now open. Someone will need to rewrite it using OpenCL/DXCompute first.

As for "mods", if you are talking about the one from NGOHQ from like 2008, that was fake.

**Comment by amoravanszky** [comment]
Zogrim is correct, of course. :)
