### ISSUE TITLE
Any change/news on the status of PhysX5.1 with Discrete Element Mtd? (F-OSS without Omniverse)

### ISSUE THREAD

**Issue by Nulled-Out** [NVIDIAGameWorks/PhysX#511]
Released as in a C++ software development kit of PhysX 5.2 for making our own software with redistributable binaries license.  🤞🏼 🙏🏼 

Wanted to ask since it's bordering 2022 when it was said to be releasing back in 2019 :/

**Comment by Daasin** [comment]
As discussed in #309 #338 & #355

**Comment by Nulled-Out** [comment]
As discussed in #309 #338 & #355 (Along with others) 
 
 _Request For Comment From:_ 
 @NvPhysX   @NvidiaGameWorksAdmin   @PierreTerdiman  @kstorey-nvidia  @ayoub-belarbi  @sschirm
