### ISSUE TITLE
Link errors on Linux, same collection of libs work on Windows except PhysXTask which isn't produced.

### ISSUE THREAD

**Issue by datgame** [NVIDIAGameWorks/PhysX#53]
On Windows, I use `PhysX_64 PhysXCommon_64 PhysXCooking_64 PhysXExtensions_static_64 PhysXFoundation_64 PhysXPvdSDK_static_64 PhysXTask_static_64`
But Linux lacks the last one. All other are built, no error shown in the end.
The build process prints
`[ 34%] Built target PhysXTask`
but no such lib is available for linking. Maybe that's the reason for these:
`physxcooking/src/Cooking.cpp:97: undefined reference to `physx::shdfnd::FPUGuard::FPUGuard()'`

`pvd/src/PxPvdDataStream.cpp:784: undefined reference to physx::shdfnd::Time::getCurrentCounterValue()'`
I know ordering during linking can be a problem on Linux too. I tried switching them around a bit with no luck.

**Comment by AlesBorovicka** [comment]
Hi,
 on linux you dont need to link against PhysXTask, as that project is build as an object file and linked into PhysX static library.
The undefined references above are not from PhysXTask, but from PhysXFoundation, please make sure that you link in correct order. This can indeed cause some trouble and is a source of linking issues sometimes. 
This is the linking order we have in our snippets and other internal projects that works for us:
PhysX PhysXExtensions PhysXCharacterKinematic PhysXCooking PhysXFoundation PhysXVehicle PhysXPvdSDK
Regards,
Ales

**Comment by datgame** [comment]
Hello and thanks. I tried your advice, but it didn't work, still lots of link errors, and you didn't include PhysXCommon which is needed.
I googled a bit and got reminded of this:
`linker works from left to right, so put all your dependent libraries on the left, and the ones that satisfy those dependencies on the right of the link line`
Using nm + grep i found what contained what, and here's my working order of libs:
`PhysX PhysXPvdSDK PhysXExtensions PhysXCooking PhysXCommon PhysXFoundation`
I don't use the vehicle and characterkinematic libs at the moment.

**Comment by datgame** [comment]
Here's a universal "solution" I had to apply in the end anyway. Works on all projects.
(in zsh on linux)
in PhysX/physx/bin/linux.clang/debug/repack
for x in ../libPhysX*; ar x $x 
ar rcs ../libphysxrepack.a *.o
and link to that single file instead

and here's how you can make a shared object afterwards:
clang++ *.o -shared -o ../libphysxrepack_so.so
