### ISSUE TITLE
How can I get list of all the available actors in a scene?

### ISSUE THREAD

**Issue by GasimGasimzada** [NVIDIAGameWorks/PhysX#539]
The `getActors` function requires creating an array of actors; so, it can copy the values into it. I want something similar to `getActiveActors` but instead of getting changed actors, get all the available actors in the scene before running the simulation.

**Comment by Pierre-Terdiman** [comment]
`getActors()` does not require creating an array. You can use the `startIndex `parameter to retrieve actors one at a time, without creating an array. It's just less efficient.

**Comment by GasimGasimzada** [comment]
Makes sense thankd!
