### ISSUE TITLE
Visual Studio 2022 support soon?

### ISSUE THREAD

**Issue by lotusblue963** [NVIDIAGameWorks/PhysX#563]
generate_projects.bat doesn't work for me. does anyone know if they will update the SDK to support Visual Studios 2022? I'm not in any particular rush or anything but I was wondering if anyone can confirm if someone is working on it and/or an estimate as to when it'll be available. I hope I didn't confuse anyone

**Comment by slackchen** [comment]
You can visit here: https://github.com/NVIDIAGameWorks/PhysX/pull/577
and merge it. I've created a pull request for this.

**Comment by lotusblue963** [comment]
oh thank you so much
