### ISSUE TITLE
if i create dynamic actor. getGlobalPose().p.y says "-nan(ind)"

### ISSUE THREAD

**Issue by Serkan4152** [NVIDIAGameWorks/PhysX#579]
but this problem does not happen with static actor

**Comment by kstorey-nvidia** [comment]
I think we'll need a lot more information to be able to help - does this happen immediately after creating the actor? Does it happen after simulation? What is the configuration of your actor?

**Comment by Serkan4152** [comment]
I fixed the problem.  It's because of PxTransform
