### ISSUE TITLE
PhysX Visual Debugger no longer available

### ISSUE THREAD

**Issue by Gobbles** [NVIDIAGameWorks/PhysX#585]
Per the title, the visual debugger no longer appears to be available. 
4.1 documentation here: https://gameworksdocs.nvidia.com/PhysX/4.1/documentation/physxguide/Manual/VisualDebugger.html#pvd
gives a download location which leads to https://developer.nvidia.com/gameworksdownload#?dn=physx-physx-visual-debugger-pvd-3-0, however none of the PVD download links in there actually leads to the PVD.

**Comment by preist-nvidia** [comment]
![image](https://user-images.githubusercontent.com/66367163/178993062-ccf19f10-f118-4bde-b5da-73bd3794a0a9.png)

Both version 2 and 3 should be available - just type PVD in the search field, top left in screenshot.

**Comment by preist-nvidia** [comment]
Ah, now I understand and can reproduce - the file I download from a release tab seems to be random. I will reported it, thank you for letting us know.

**Comment by marvkey** [comment]
When I download, I get error Maya LT not downloaded.

**Comment by Gobbles** [comment]
Download links have been restored
