### ISSUE TITLE
 conversion from PxRigidDynamic to PxRigidStatic and vice versa 

### ISSUE THREAD

**Issue by hanseul1795** [NVIDIAGameWorks/PhysX#60]
I'm implementing a simple physics simulator and I wanted to know if it's possible to convert PxRigidDynamic to PxRigidStatic.
Thank you!

**Comment by kstorey-nvidia** [comment]
Not directly. You could manually convert it by moving the shapes to a new PxRigidStatic.

An alternative (which would be slightly slower but perfectly functional) is to set PxRigidBodyFlag::eKINEMATIC flag on the PxRigidDynamic. This will have the effect of making the rigid body become infinite mass body. If you don't set a kinematic target on the body, it will not move and behave like a static body.

**Comment by hanseul1795** [comment]
Thank you!
