### ISSUE TITLE
What are required files (source/headers) to link PhysX 4.0 into my own CMake project?

### ISSUE THREAD

**Issue by hanseul1795** [NVIDIAGameWorks/PhysX#63]
I've copy pasted all src/include files from physx and pxshared. rebuilt physX to create static libraries.
But it seems like some paths to headers are missing and create "unresolved symbol" issue.

> Warning
 LNK4217 locally defined symbol PxCreateFoundation imported in function "public: bool __cdecl Chaos::Physics::PhysXInitializer::InitPhysX(void)" (?InitPhysX@PhysXInitializer@Physics@Chaos@@QEAA_NXZ)

> Error LNK2019 unresolved external symbol __imp_PxCreateCooking referenced in function "public: bool __cdecl Chaos::Physics::PhysXInitializer::InitPhysX(void)" (?InitPhysX@PhysXInitializer@Physics@Chaos@@QEAA_NX

Is there a CMake file that I can get to see how source files are linked in CMake?

Thank you!

**Comment by AlesBorovicka** [comment]
Hi,
 not sure I understand your question, but if you would like to see what directories are needed for include path and what libraries are required to be linked, then you can take a look at the snippet projects. For exmplae SnippetTemplate.cmake
Includes:
	PRIVATE ${PHYSX_ROOT_DIR}/include/
Libraries:
	PUBLIC PhysX PhysXExtensions PhysXCharacterKinematic PhysXCooking PhysXFoundation PhysXVehicle PhysXPvdSDK

Regards,
Ales
