### ISSUE TITLE
is physx visual debugger open sourced?

### ISSUE THREAD

**Issue by BackMountainBird** [NVIDIAGameWorks/PhysX#634]
I see pvd is only available for  binary download for now. Is it possible it get open sourced ?

**Comment by preist-nvidia** [comment]
Hi @BackMountainBird - no there is no plan to open source the PVD code, and it's support is deprecated in PhysX 5.

It is not complete yet, but please check out omnipvd that we are actively developing https://docs.omniverse.nvidia.com/prod_extensions/prod_extensions/ext_omnipvd.html
