### ISSUE TITLE
Not getting invite email 

### ISSUE THREAD

**Issue by sauravkumar8178** [NVIDIAGameWorks/PhysX#637]
I am filling the form for access Nvidia Gameworks Source but I am not getting invitation mail. 
According to eula it's taking one hours but I am not getting any response.

**Comment by preist-nvidia** [comment]
What are you trying to do?

**Comment by sauravkumar8178** [comment]
Okay, I am currently pursuing game development course in XAMK Open University. So I will learning more in game development and contributing my skill in open source project.

**Comment by sauravkumar8178** [comment]
That why I need access

**Comment by preist-nvidia** [comment]
Ok got it. Two things:
- you can get the code here without signing up, and you should consider using the new 5.1 version here: https://github.com/NVIDIA-Omniverse/PhysX
- Contributing is indirect - we look at pull requests and then review, test, and merge them internally, before they will make it back to the public repo.

**Comment by sauravkumar8178** [comment]
Understood, Thank you
