### ISSUE TITLE
set kine-kine flag is not working

### ISSUE THREAD

**Issue by Durumyisking** [NVIDIAGameWorks/PhysX#650]
![q1](https://github.com/NVIDIAGameWorks/PhysX/assets/80432748/db87b879-3935-4186-bc56-3e93a181cd31)
I set the kinekineFilteringMode to "Keep" when creating the PxScene.
(When I later called scene.getkinekinefilteringmode(), it correctly returned "Keep" even when I had set it to "Kill" or something else.)

![q2](https://github.com/NVIDIAGameWorks/PhysX/assets/80432748/c5bd46e4-bf1f-43a5-af07-18d56fda9b8a)
When specifying the actor type as "kinematic," I set the RigidDynamic.setRigidBodyFlags to "Kinematic" and enabled "eForceKineKineNotification."

![q3](https://github.com/NVIDIAGameWorks/PhysX/assets/80432748/3cbb7098-fc5d-4a3c-ba5d-76ab2ef0ba77)
![q4](https://github.com/NVIDIAGameWorks/PhysX/assets/80432748/111b8c62-e704-4057-b286-705852bfe51a)
However, it is not recognized in PVD (PhysX Visual Debugger). The values I had set are correctly retrieved in the Visual Studio debugger. (The behavior in the game also does not follow my intentions, as it only checks collisions between kinematic and static objects, but not between kinematic objects.)

![q6](https://github.com/NVIDIAGameWorks/PhysX/assets/80432748/79480d78-abcb-4473-9e80-6f841254e6d0)
I changed the shape's flag to a trigger shape.

![q5](https://github.com/NVIDIAGameWorks/PhysX/assets/80432748/82b00b9a-aa47-4de5-8443-507b80efd3b6)
This is the custom filter shader I created for the creation of the PxScene. It inherits from PxQueryFilterCallback.

![q7](https://github.com/NVIDIAGameWorks/PhysX/assets/80432748/37111ade-01c3-4ef6-ae2d-2f473a23d0f4)
This is the part that handles callback processing when collisions occur. It inherits from PxSimulationEventCallback.
(When there is a collision between static and kinematic objects, it correctly enters the
` if (pair.status & PxPairFlag::eNOTIFY_TOUCH_FOUND) flag.`
However, when there is a collision between kinematic objects, it does not enter the onTrigger function itself.)

**Comment by vreutskyy** [comment]
Hello. Sorry I didn't understand if your PlayerFilter shader function gets called for the kinematic bodies pair or not?
It seems it should. Then you just need to set some PxPairFlag::eNOTIFY_* flags to get onContact() callback called for this pair.
Or do I miss something?

**Comment by preist-nvidia** [comment]
Closing for now. Please reopen if you get a chance to respond. Internal PX-4433.
