### ISSUE TITLE
Strange URLs on NVIDIA PhysX Website

### ISSUE THREAD

**Issue by lordbendtner1337** [NVIDIAGameWorks/PhysX#656]
There are some really strange URLs on the NVIDIA PhysX website; https://www.nvidia.com/en-us/drivers/physx-downloads/

The "PhysX Developers Website" button redirects you to https://supportcenteronline.com/ics/support/default.asp?deptID=1949

The "Tool Vendor Verification System" button redirects you to https://www.warioworld.com/tvvs/nvidia/

**Comment by preist-nvidia** [comment]
Hi @lordbendtner1337 - thanks for the report, I see the weird supportcenter link, but cannot access. Will investigate!

**Comment by preist-nvidia** [comment]
Thanks again for the report, we'll replace this obsolete page with a redirect to our current SDK landing: https://developer.nvidia.com/physx-sdk
