### ISSUE TITLE
Can I use Mingw instead of VC to compile it?

### ISSUE THREAD

**Issue by Q3dlaXpoaQ** [NVIDIAGameWorks/PhysX#663]
I only had Mingw and  I want to compile it. Can I compile it by Mingw?

**Comment by vreutskyy** [comment]
Hi @Q3dlaXpoaQ 
We only support VC on Windows, and Clang on Linux.
https://gameworksdocs.nvidia.com/PhysX/4.1/documentation/platformreadme/windows/readme_windows.html
https://gameworksdocs.nvidia.com/PhysX/4.1/documentation/platformreadme/linux/readme_linux.html

**Comment by Q3dlaXpoaQ** [comment]
Thanks you.
