### ISSUE TITLE
Code conventions

### ISSUE THREAD

**Issue by Jamim** [NVIDIAGameWorks/PhysX#7]
Hello,

I just opened a [random source code file](https://github.com/NVIDIAGameWorks/PhysX/blob/4.0.0/physx/source/task/src/TaskManager.cpp) and I see a [lack of consistency in terms of indents](https://github.com/NVIDIAGameWorks/PhysX/blob/4.0.0/physx/source/task/src/TaskManager.cpp#L158-L167).
There are some mixes of [tab and space characters](https://github.com/NVIDIAGameWorks/PhysX/blob/4.0.0/physx/source/task/src/TaskManager.cpp#L195-L213).

Are there code conventions which contributors have to follow?

Thanks!

**Comment by amoravanszky** [comment]
Yes, more consistency would be nice, and yes we do have internal coding conventions.  But we would be surprised to receive a large volume of contributions that go beyond small fixes that are easy to reformat.  For the time being just try to follow the style used in the code that you are editing.
