### ISSUE TITLE
Missing CMake error when running generate_projects.bat in Windows

### ISSUE THREAD

**Issue by JDAlzate** [NVIDIAGameWorks/PhysX#76]
I'm trying to generate the projects for PhysX with the generate_projects.bat file but I keep getting the same error: "Cmake is missing, please install cmake version 3.12 and up."
The error is pretty obvious but I have already installed CMake.
I'm not sure if there is a specific directory I should install CMake on, I have never worked with CMake before. Right now, it's installing in the default program files folder.

**Comment by nov-ta** [comment]
It probably has to be available on path, try running "where cmake" from a cmd window and see what pops up. That's what generate_projects.bat uses to find cmake. In my case it's part of user path:

![image](https://user-images.githubusercontent.com/47320028/53622539-70b0ab80-3bfa-11e9-8bee-ba32cbbde6d8.png)

**Comment by JDAlzate** [comment]
I'm not sure what the problem was. I just uninstalled CMake and installed it again and it worked just fine.
Thank you for your help though, I appreciate it.
