### ISSUE TITLE
How to raycast against random solids / How to efficiently set collision behavior(On contact modify?) for each actors.

### ISSUE THREAD

**Issue by hanseul1795** [NVIDIAGameWorks/PhysX#78]
1- I'm trying to raycast from a dynamic actor to random solides by setting the starting position, normal, distance.
The problem is, from the documentation, it seems like I need to set the geometry(the geometry to test against) and the pose(the transform of the geometry).  Is there a way to raycast against random solids and retreive all the raycast information ?

2- To modify the collision behavior(from contact) I see that I need to inherit callback class from PhysX and override OnContactModify method than set it in Scenedesc. 
What I'd like to know is, like in Unreal engine, I want to modify contact behavior for each actors. 
I don't know if it would be a good practice to implement everything in one OnContactModify method. 
Thank you!
Hans

**Comment by AlesBorovicka** [comment]
Hi,
 you can raycast directly against a geometry, then as you pointed out you need to provide that geometry and its transformation, that is a PxGeometryQuery::raycast.
But you can also call PxScene::raycast where it will make a raycast against all shapes in a scene with the eSCENE_QUERY_SHAPE flag.

Ales
