### ISSUE TITLE
Error when running physx/generate_projects.sh 

### ISSUE THREAD

**Issue by arrfou90** [NVIDIAGameWorks/PhysX#8]
When excuting the shell script **generate_projects.sh**, I go this undefined error. 

> 
> Using preset xml: /home/nvidia/PhysX/physx/buildtools/presets/public/linux-aarch64.xml
> Target platform: linuxAarch64 using compiler: gcc
> PM_CMakeModules_PATH: /home/nvidia/PhysX/physx/../externals/cmakemodules
> PM_PATHS: /home/nvidia/PhysX/physx/../externals/opengl-linux
> Cmake: cmake
> sh: 1: cmake: not found
> sh: 1: cmake: not found
> sh: 1: cmake: not found
> sh: 1: cmake: not found
> 
After debugging, I figuerd out the error was becuase I did not have cmake installed in my system. Also, notice that for compiling CMake 3.12 or higher is required!

**Comment by sheikh-nv** [comment]
Yes. CMake 3.12 is a requirement. Apologies, this is not explicitly noted in our readme. We are updating the readme soon.

**Comment by ericwomer** [comment]
It works fine with cmake 3.10 on my system, I just changed this file physx/compiler/public/CMakeLists.txt as seen below with the git diff/patch

```

diff --git a/physx/compiler/public/CMakeLists.txt b/physx/compiler/public/CMakeLists.txt
index a3f5731..ebce46d 100644
--- a/physx/compiler/public/CMakeLists.txt
+++ b/physx/compiler/public/CMakeLists.txt
@@ -25,7 +25,7 @@
 ##
 ## Copyright (c) 2018 NVIDIA Corporation. All rights reserved.
 
-cmake_minimum_required(VERSION 3.12)
+cmake_minimum_required(VERSION 3.10)
 
 project(PhysXSDK C CXX)
 
@@ -163,4 +163,4 @@ IF(PX_BUILDPUBLICSAMPLES)
                SET_PROPERTY(TARGET SampleRenderer PROPERTY FOLDER "PhysX Samples")
 
        ENDIF()
-ENDIF()
\ No newline at end of file
+ENDIF()

```

The problem with setting it to 3.12 is that Ubuntu 18.04 (LTS) only has cmake 3.10, is there a specific reason for wanting cmake 3.12 or what is just the one what was used when the CMakeLists.txt file was written?

**Comment by AlesBorovicka** [comment]
Yes, cmake 3.12 is required as it fixes issues with latest xcode on mac. Lower version might be fine on linux though, but in general we require 3.12 because of xcode. On windows it might be 3.10-3.11 that is fine, there were some issues with vs2017... 

Maybe we will have to lower it for some platforms... even though I wanted to avoid that. But if its a bit complicated on linux we could lower that on linux indeed.

**Comment by ericwomer** [comment]
I don't believe you need to change anything, just mention it somewhere as its just an easy fix, eventually Ubuntu will get around to installing cmake-3.12 (25.25 Futuristic Beaver or something.)

**Comment by ericwomer** [comment]
As a side note, I just found out about this, so even on a system that doesn't install cmake >= 3.12 there is the cmake that you can install via pip, here is the [cmake](https://pypi.org/project/cmake) pip page, and here are the cmake pip install commands.

For users local copy
> pip install --user cmake

For system wide install
>sudo pip install cmake

So you can put that in your documentation somewhere in case they are on an older Linux system.

**Comment by AlesBorovicka** [comment]
Thanks! I will add this to the documentation - the linux readme file.

**Comment by AlesBorovicka** [comment]
Doc updated, changes will appear in next patch update
