### ISSUE TITLE
How to set the rigidbody for character controller?

### ISSUE THREAD

**Issue by hanseul1795** [NVIDIAGameWorks/PhysX#81]
Hello~
I'm learning how to use the Character controller and came up with 2 questions.
1- Is it possible to assign a character controller to an existing dynamic body in the scene?
2- In the documentation, there is no explanation about customizing the inputs. I'd like to know how can I set up the inputs. 

Thank you!

**Comment by PierreTerdiman** [comment]
Hello,

1. No, this is currently not possible. Each character controller will create its own embedded kinematic actor, and there is no API to pass an existing scene actor to the character controller. The character controller module only works with kinematic actors containing one single shape, and that shape must be a box or a capsule. So while we could pass an existing scene actor to the character controller, it would have to be stricly checked and there would be quite a few limitations for accepting the actor. That would be quite error-prone, and it is a lot easier to just let the character controller create whatever actor is needed.

2. I do not understand what you mean with "customizing the inputs". There is an API to move the characters around (PxController::move()). The main element is a simple displacement vector ("disp") provided by the user. It is fully under user's control, so all the "customization" would happen in your game code, when computing this input vector.
