### ISSUE TITLE
Does PhysX integrate with ROS?

### ISSUE THREAD

**Issue by vaibhavviswanathan** [NVIDIAGameWorks/PhysX#9]

**Comment by NvPhysX** [comment]
PhysX integration with ROS can be done at the application level. Internally we are working with a UE4/PhysX-4 based simulator that offers a ROS messaging interface to external clients.  We intend to release this code within a few months.

**Comment by yjiang0929** [comment]
Hi we are a team of researchers based in Singapore and we would be interested to try PhysX for robotics simulation. Can you provide an update on when this simulator will be released and if we may use some early access versions for our experiment? Thanks
